server:
  port: 9000
spring:
  application:
    name: upload-server-9000
eureka:
  instance:
    prefer-ip-address: true
    instance-id: upload-server
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
upload:
  url: D:\temp\photos