server:
  port: 8001
spring:
  application:
    name: mall-product-brand-8001
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/mall
mybatis:
  configuration:
    map-underscore-to-camel-case: true    #驼峰字段映射
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  auto-dialect: true
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: product